publishDir = "docs"
baseurl = "https://xaviablaza.github.io/stellar-gcash-anchor/"
languageCode = "en-us"
title = "GCash Anchor for Stellar Network"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Xavi Ablaza"
	description = "GCash Anchor for the Stellar Network"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Xavi Ablaza**, and I'm trying<br>to make a GCash Anchor<br>for the [Stellar Network](https://stellar.org)."
		# The icons will be shown if you enter your username
		twitter = ""
		github = "xaviablaza"
		gitlab = ""
		dribbble = ""
		facebook = "xlablaza"
		googleplus = ""
		flickr = ""
		linkedin = "xaviablaza"

		copyright = [
			"&copy; Xavi Ablaza 2017",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "xaviablaza's GCash PHP Anchor for the Stellar Network"
		content = "This anchor is a proof of concept for PHPG credit to be issued and exchanged on the Stellar network. Hopefully, we can make our e-money systems in the Philippines more interoperable."


	[params.portfolio]
		hide  = true
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "You can reach out to me through email if you have any questions or concerns."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "33.792826,-117.8519811"
		address = [
			"1 University Dr.",
			"Attn: Argyros Forum 303",
			"Orange, CA 92866",
			"United States"
		]
		phone = "714-588-7523"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "xlablaza@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
#[[menu.main]]
#	name = "Home"
#	url  = "/"
#	weight = 10
#
#[[menu.main]]
#	name = "Blog"
#	url  = "post/"
#	weight = 0
